### ISSUE TITLE
Make "Date of recording" field actually show capture date instead of upload date

### ISSUE THREAD

**Issue by ToeBee** [openstreetcam/openstreetcam.org#44]
Right now the `Date of recording` field on the picture detail page actually shows the date the picture was uploaded, not the date it was recorded. This field should display info from the EXIF timestamp. I think `Date/Time Original` but I see several date fields in the EXIF tags so you might need to fall back to other fields if that one is blank.

For bonus points, the date shown on the sequence from the user profile page could also be set to the time of the first picture in the sequence instead of the upload date. This one is more of UI design question of what that field should display though.

I am currently uploading pictures taken in 2015 but the date on all of them shows as August 2016.

**Comment by james2432** [comment]
This could be checked via exif data, and if not available you could default to upload date

**Comment by hbogner** [comment]
Please fix this issue. I want to be able fo find photo sequences by date of recording, not by date of upload.... cc @martijnv-telenav

**Comment by ToeBee** [comment]
Re-ping on this as well. The double upload bug in the upload script has me needing to find sequences by date of recording as well so I can track down which ones were affected.

**Comment by mvexel** [comment]
https://twitter.com/KSUToeBee/status/927992121017151489

**Comment by hbogner** [comment]
Re-ping. Any progress on this bug? I want to start uploading when this bug is fixed.

**Comment by bogdan-telenav** [comment]
Hi @hbogner Can you provide some images ? I want to test it and if this is fixed i will let you know asap. I fixed some things and i want to test it with different images

**Comment by bogdans-telenav** [comment]
We provide a field on each photo that is the recording date called shot_date. I will close this since it was addressed if you consider otherwise please reopen it with updated details.

**Comment by hbogner** [comment]
Please DO NOT CLOSE this issue until the problem is fixed!!!
NO, this was not addressed, just discarded!!!

I did a demonstration to try and explain the problem in more detail:
First i deleted all my uploaded sequences to remove confusion.
Then 3 random sequences were selected for this demonstration purposes, one from 2014. one from 2016. and one from 2018., and they were uploaded in random order.
They were all reported as from  today/yesterday.

Try to guess which sequence is from which year!!!

Here is a screenshot 
![openstreetcam](https://user-images.githubusercontent.com/794472/53688946-dfe9e500-3d4b-11e9-9fe4-8f82e79f23d7.png)
and a link to the web: https://openstreetcam.org/user/hbogner

Now imagine what will happen when few more thousand sequences(waiting on the local drives) are added!!! Try and find a sequence then...

As I stated before, and as I stated to your team at SotM 2018, I'll won't upload my sequences until you fix this problem.

**Comment by hbogner** [comment]
There is no way for me to reopen this issue so please be kind and reopen this not fixed issue.

**Comment by hbogner** [comment]
I can provide those 3 sequences for download, as they are, if needed.
But please fix the date field.
Date of upload is of no importance to users, at least to me. 
Date of sequence creation is what is important, and it should be sorted that way.

**Comment by bogdans-telenav** [comment]
@hbogner Sorry for the misunderstanding. We addressed this issue for sequences that are recorded with our apps but for sequences recorded with third party cameras we currently do not a solution.
I could try to generate a OSC metadata file from your images having exif and upload them with a metadata file, this would solve your issue.

**Comment by hbogner** [comment]
I have images from before OSC, so they could not be taken with the default app :)
They are action camera images or mapillary images, both having exif data.
Would this generation of OSC metadata be a part of https://github.com/openstreetcam/upload-scripts ?
No problem, I plan to delete them and re upload everything when this issue is fixed.

PS. Do you know does upload-scripts split sequences based on time&distance data?

**Comment by bogdans-telenav** [comment]
> Would this generation of OSC metadata be a part of https://github.com/openstreetcam/upload-scripts ?
Yes

**Comment by ToeBee** [comment]
I see the web UI has been changed to say `Date of upload` for action camera tracks. So you didn't change the data being shown, just the label. For mapping purposes I really don't care when an image was uploaded, just when it was captured. This affects iD and JOSM as well. JOSM doesn't show *any* date for action camera tracks and iD shows the upload date, not the capture date. Seeing cyclists in shorts and mid-summer greenery in Wyoming with the only date visible being "November 2" is definitely doing to confuse someone at some point :) https://openstreetcam.org/details/1303627/4/track-info
